name: momen-khaled-id-2023040182 

on:
  push:
    branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'testing github action'
      run: pwd
      
    - name: 'testing printing'
      run: echo momen
      

   
      
    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          YOUR_DOCKER_USERNAME/momen_khaled_2023040182:latest 
        file: ./Dockerfile