name: momen-khaled-id-2023040182 

on:
  push:
    branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'printing folder contents'
      run : ls
      
    - name: 'testing printing'
      run: echo momen
      
    - uses : actions/checkout@v3

    - name: 'printing folder contents'
      run : ls
      
    